[project]
name = "caosgame"
version = "0.1.0"
description = "Interactive visualization of 1D chaotic systems"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "matplotlib",
    "streamlit"
]
